### ISSUE TITLE
Race conditions if ozy tries to install the same executable at the same time

### ISSUE THREAD

**Issue by mattgodbolt** [aquanauts/ozy#18]
Seems like we'd need a locking mechanism to await, if a new app `app` is invoked twice, e.g.

```sh
$ app &
$ app &  # may race installation with the above
```

**Comment by mattgodbolt** [comment]
Importantly any locking must _not_ block multiple invocations, just multiple installations.

**Comment by mattgodbolt** [comment]
Trace from a suspected failure of this type:
```
[16:15:51] 100%|██████████| 45.4M/45.4M [00:00<00:00, 251MiB/s][243] Failed to execute script ozy
[16:15:51] 
[16:15:51] Traceback (most recent call last):
[16:15:51]   File "ozy/app.py", line 79, in install
[16:15:51] FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/ozy/vault/1.2.3.tmp' -> '/root/.cache/ozy/vault/1.2.3'
[16:15:51] 
[16:15:51] During handling of the above exception, another exception occurred:
[16:15:51] 
[16:15:51] Traceback (most recent call last):
[16:15:51]   File "ozy", line 12, in <module>
[16:15:51]   File "ozy/__main__.py", line 266, in app_main
[16:15:51]   File "ozy/__main__.py", line 246, in _run
[16:15:51]   File "ozy/app.py", line 86, in ensure_installed
[16:15:51]   File "ozy/app.py", line 81, in install
[16:15:51]   File "shutil.py", line 476, in rmtree
[16:15:51]   File "shutil.py", line 474, in rmtree
[16:15:51] FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/ozy/vault/1.2.3.tmp'
[16:15:51] [241] Failed to execute script ozy
```
